#!/usr/bin/env python3

"""
Are you bored?? This program will generate
a random activity for you to do.

Created With: 'The Bored API' [https://www.boredapi.com/]
Created By: D34D9001
Jan. 10, 2022
"""

import requests
import sys
import json
import getopt
from termcolor import colored

argv = sys.argv[1:]

if len(argv) == 0:
    print("[Invalid] Please Try Again\nbored -f [# of friends]")
    sys.exit()

try:
    total = len(sys.argv)
    if int(total) < 1:
        print("[Invalid] Please Try Again\nbored -s/-f [# of friends]")
        sys.exit()
    else:
        options, args = getopt.getopt(argv, "f:sh",
                                   ["friends =",
                                    "solo",
                                    "help"])
        for name, value in options:
            if name in ['-f', '--friends']:
                friends = value

                if int(friends) <= 1:
                    print("You have no friends...\nTry: ./bored -s")
                    sys.exit()
                if int(friends) >= 9:
                    print("You have too many friends...")
                    sys.exit()

                else:
                    r = requests.get("http://www.boredapi.com/api/activity?participants=%s" % str(friends))
                    r = r.json()
                    print("http://www.boredapi.com/api/activity?participants=%s" % str(friends))
                    print("[7H3 80R3D 491]:\n                   Are you bored? Maybe you should...\n")
                    print("                   [Activity]: " + str(r['activity']))
                    if float(r['accessibility'] >= .5):
                        print(colored("                   [Accessibility]: " + str(r['accessibility']), 'red', attrs=['bold']))
                    else:
                        print(colored("                   [Accessibility]: " + str(r['accessibility']), 'green', attrs=['bold']))
                    print("                   [Type]: " + str(r['type']))
                    print("                   [Participants]: " + str(r['participants']))
                    if float(r['price'] >= .5):
                        print(colored("                   [Price]: " + str(r['price']), 'red', attrs=['bold']))
                    else:
                        print(colored("                   [Price]: " + str(r['price']), 'green', attrs=['bold']))
                    print("                   [Link]: " + str(r['link']))
                    print("                   [Key]: " + str(r['key']))
            elif name in ['-s', '--solo']:
                r = requests.get("http://www.boredapi.com/api/activity?participants=1")
                r = r.json()
                print("[7H3 80R3D 491]:\n                   Are you bored? Maybe you should...\n")
                print("                   [Activity]: " + str(r['activity']))
                if float(r['accessibility'] >= .5):
                    print(colored("                   [Accessibility]: " + str(r['accessibility']), 'red', attrs=['bold']))
                else:
                    print(colored("                   [Accessibility]: " + str(r['accessibility']), 'green', attrs=['bold']))
                print("                   [Type]: " + str(r['type']))
                print("                   [Participants]: " + str(r['participants']))
                if float(r['price'] >= .5):
                    print(colored("                   [Price]: " + str(r['price']), 'red', attrs=['bold']))
                else:
                    print(colored("                   [Price]: " + str(r['price']), 'green', attrs=['bold']))
                print("                   [Link]: " + str(r['link']))
                print("                   [Key]: " + str(r['key']))
            elif name in ['-h', '--help']:
                print("[Usage:] ./bored -f [friends]")
                print("-f should be an int (# of participants)")
                sys.exit()
            else:
                print("[Usage:] ./bored -f [friends]")
                print("-f should be an int (# of participants)")
                sys.exit()
except Exception as error:
    print(error)
    sys.exit()
